services:
  tarantool:
    image: tarantool/tarantool:2.10
    platform: linux/amd64
    ports:
      - "3301:3301"
    environment:
      - TARANTOOL_INSTANCE_NAME=events_queue
      - TARANTOOL_USER_NAME=test
      - TARANTOOL_USER_PASSWORD=test
    volumes:
      - ./tarantool:/opt/tarantool
    command: ["tarantool", "/opt/tarantool/init.lua"]